### ISSUE TITLE
 gemeenten huis

### ISSUE THREAD

**Issue by Daanv208** [MiddelvoorsteRP/development#14]
-als je een zorg verzekering wilt aan vragen dan word je gekickt en in beeld staat dan (Mag niet he)
-vlieg bevret kan je niet aanvragen geld het zelfde voor ID en rijbewijs

**Comment by nickvmeurs** [comment]
- [x] Zorg verzekering wordt zal ik zo naar kijken
- [x] Vlieg bevret kan je alleen halen als er in de DB staat dat je een vliegbevret hebt
- [x] ID en Rijbewijs zal ik zo bekijken

Bedankt voor het melden

**Comment by nickvmeurs** [comment]
Fixed bedankt
