### ISSUE TITLE
sloten gang en rang 

### ISSUE THREAD

**Issue by onfirenl** [MiddelvoorsteRP/development#9]
ik wil op mijn kantor een slot en ik wil dat supoort niet in de kleus kan ook ze mogen ook geen wapen  of zo kopen geld het zelfde voor job 2 porspect

en aleen ik kan in het manegemet menu met vprasidant

wapen in koop werkt nie
f6 werkt nie

**Comment by nickvmeurs** [comment]
Hey,

Met je kantoor bedoel je dan waar het bossmenu is?
En welke kluis bedoel je, en wapens kopen of gereedschap kopen kan ik wel veranderen door het in een kamer te doen waar je alleen in kan als je hoger dan support of Prospect bent.

Management menu zal ik zo naar kijken

Wapen inkoop zit er nog niet in, en is op het moment nog met zwart geld. Wordt veranderd + Je hebt een voorraad en cokeblokken nodig.

Verder is er geen F6. Alles gaat via items en interactie...
- Fouilleren kan als iemand zijn handen omhoog heeft
- Afboeien kan met tiewraps
- Auto's kun je open maken met snijbranders etc etc

**Comment by nickvmeurs** [comment]
Vice President en President zijn nu de enigste die in het boss menu kunnen
